@testset "Validation policy and benchmark infrastructure" begin
    root = normpath(joinpath(@__DIR__, ".."))

    policy = read(joinpath(root, "VALIDATION_POLICY.md"), String)
    @test contains(policy, "Fast Path")
    @test contains(policy, "Manual Validation")
    @test contains(policy, "S5_VALIDATION_LARGE")
    @test contains(policy, "S5_BENCHMARK_LARGE")
    @test contains(policy, "Future Trigram Validation")
    @test contains(policy, "centered one-hot")

    readme = read(joinpath(root, "README.md"), String)
    @test contains(readme, "Complexity notation used below")
    @test contains(readme, "`n`: generated sequence length")
    @test contains(readme, "`d`: configured history depth")
    @test contains(readme, "`k`: alphabet size")
    @test contains(readme, "`I`: number of calibration iterations")
    @test !contains(readme, "| ID | Name | Status |")

    benchmark_project = read(joinpath(root, "benchmark", "Project.toml"), String)
    @test contains(benchmark_project, "BenchmarkTools")
    @test contains(benchmark_project, "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf")
    @test contains(benchmark_project, "StableRNGs")

    benchmark_readme = read(joinpath(root, "benchmark", "README.md"), String)
    @test contains(benchmark_readme, "S5_BENCHMARK_LARGE")
    @test contains(benchmark_readme, "machine-specific evidence")

    benchmark_script = read(joinpath(root, "benchmark", "benchmarks.jl"), String)
    @test contains(benchmark_script, "BenchmarkGroup")
    @test contains(benchmark_script, "S5_BENCHMARK_LARGE")
    @test contains(benchmark_script, "PB1_SpectralFGN_fft=n")
    @test contains(benchmark_script, "PB3_WaveletMarkov_spectral_regimes=2")
    @test contains(benchmark_script, "MB1a_LAMP_d=")
    @test contains(benchmark_script, "MB1b_DyadicLAMP_d=")
    @test contains(benchmark_script, "MB3_FSS_streams=")
    @test contains(benchmark_script, "MB4_HawkesSymbol_d=")

    validation_project = read(joinpath(root, "validation", "Project.toml"), String)
    @test contains(validation_project, "LongMemory")

    comparison_script = read(joinpath(root, "validation", "longmemory_comparison.jl"), String)
    @test contains(comparison_script, "LongMemory.autocovariance")
    @test contains(comparison_script, "LongMemory.autocorrelation")
    @test contains(comparison_script, "LongMemory.periodogram")

    diagnostic_script = read(joinpath(root, "validation", "lrd_method_diagnostics.jl"), String)
    @test contains(diagnostic_script, "diagnostic_lag_limit")
    @test contains(diagnostic_script, "stroke-dasharray")
    @test contains(diagnostic_script, "intrinsic_lag_limit(g::LAMP)")
    @test contains(diagnostic_script, "intrinsic_lag_limit(g::HawkesSymbol)")
    @test contains(diagnostic_script, "acf_power_law_reference")
    @test contains(diagnostic_script, "spectrum_power_law_reference")
    @test contains(diagnostic_script, "nominal ACF beta=")
    @test contains(diagnostic_script, "nominal spectrum beta=")
end
