@testset "Validation policy and benchmark infrastructure" begin
    root = normpath(joinpath(@__DIR__, ".."))

    policy = read(joinpath(root, "VALIDATION_POLICY.md"), String)
    @test contains(policy, "Fast Path")
    @test contains(policy, "Manual Validation")
    @test contains(policy, "SLMS_VALIDATION_LARGE")
    @test contains(policy, "SLMS_BENCHMARK_LARGE")
    @test contains(policy, "Future Trigram Validation")
    @test contains(policy, "centered one-hot")

    readme = read(joinpath(root, "README.md"), String)
    @test contains(readme, "Complexity notation used below")
    @test contains(readme, "`n`: generated sequence length")
    @test contains(readme, "`d`: configured history depth")
    @test contains(readme, "`k`: alphabet size")
    @test contains(readme, "`I`: number of calibration iterations")
    @test !contains(readme, "| ID | Name | Status |")

    benchmark_project = read(joinpath(root, "benchmark", "Project.toml"), String)
    @test contains(benchmark_project, "BenchmarkTools")
    @test contains(benchmark_project, "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf")
    @test contains(benchmark_project, "StableRNGs")

    benchmark_readme = read(joinpath(root, "benchmark", "README.md"), String)
    @test contains(benchmark_readme, "SLMS_BENCHMARK_LARGE")
    @test contains(benchmark_readme, "SLMS_BENCHMARK_SCALING")
    @test contains(benchmark_readme, "SLMS_BENCHMARK_SYNTH_REPEATS")
    @test contains(benchmark_readme, "machine-specific evidence")
    @test contains(benchmark_readme, "benchmark/RESULTS.md")
    @test contains(benchmark_readme, "relative_times_k*_n*.svg")

    benchmark_script = read(joinpath(root, "benchmark", "benchmarks.jl"), String)
    @test contains(benchmark_script, "BenchmarkGroup")
    @test contains(benchmark_script, "SLMS_BENCHMARK_LARGE")
    @test contains(benchmark_script, "SLMS_BENCHMARK_SCALING")
    @test contains(benchmark_script, "SLMS_BENCHMARK_SYNTH_REPEATS")
    @test contains(benchmark_script, "SCALING_NS = (100, 1_000, 10_000, 100_000, 1_000_000)")
    @test contains(benchmark_script, "SCALING_KS = (2, 8)")
    @test contains(benchmark_script, "SLMS_BENCHMARK_WRITE_RESULTS")
    @test contains(benchmark_script, "write_relative_time_svg")
    @test contains(benchmark_script, "write_scaling_svg")
    @test contains(benchmark_script, "PB1_SpectralFGN_fft=n")
    @test contains(benchmark_script, "PB3_WaveletMarkov_spectral_regimes=2")
    @test contains(benchmark_script, "PB4_IntermittentMapSymbols_z=1.6")
    @test contains(benchmark_script, "MB1a_LAMP_d=")
    @test contains(benchmark_script, "MB1b_DyadicLAMP_d=")
    @test contains(benchmark_script, "MB1c_CalibratedAdditiveMarkov_d=")
    @test contains(benchmark_script, "MB3_FSS_streams=")
    @test contains(benchmark_script, "MB4_HawkesSymbol_d=")
    @test contains(benchmark_script, "MB5_DuplicationMutation_alpha=1.5")

    validation_project = read(joinpath(root, "validation", "Project.toml"), String)
    @test contains(validation_project, "LongMemory")

    comparison_script = read(joinpath(root, "validation", "longmemory_comparison.jl"), String)
    @test contains(comparison_script, "LongMemory.autocovariance")
    @test contains(comparison_script, "LongMemory.autocorrelation")
    @test contains(comparison_script, "LongMemory.periodogram")

    diagnostic_script = read(joinpath(root, "validation", "lrd_method_diagnostics.jl"), String)
    @test contains(diagnostic_script, "diagnostic_lag_limit")
    @test contains(diagnostic_script, "write_diagnostic_pair_svg")
    @test contains(diagnostic_script, "_diagnostics.svg")
    @test contains(diagnostic_script, "stroke-dasharray")
    @test contains(diagnostic_script, "intrinsic_lag_limit(g::LAMP)")
    @test contains(diagnostic_script, "intrinsic_lag_limit(g::CalibratedAdditiveMarkov)")
    @test contains(diagnostic_script, "intrinsic_lag_limit(g::HawkesSymbol)")
    @test contains(diagnostic_script, "intrinsic_lag_limit(g::DuplicationMutation)")
    @test contains(diagnostic_script, "asymptotic_lag_threshold")
    @test contains(diagnostic_script, "approx. power-law onset")
    @test contains(diagnostic_script, "slope_fraction * g.c / (1 - slope_fraction)")
    @test contains(diagnostic_script, "acf_power_law_reference")
    @test contains(diagnostic_script, "spectrum_power_law_reference")
    @test contains(diagnostic_script, "nominal ACF beta=")
    @test contains(diagnostic_script, "nominal spectrum beta=")
end
